
// From libdisk/format/unformatted.c
X(unformatted,             "Unformatted")

// From libdisk/format/raw.c
X(raw_sd,                  "Raw SD")
X(raw_dd,                  "Raw DD")
X(raw_hd,                  "Raw HD")
X(raw_ed,                  "Raw ED")

X(variable_raw_sd,         "Variable-Rate Raw SD")
X(variable_raw_dd,         "Variable-Rate Raw DD")
X(variable_raw_hd,         "Variable-Rate Raw HD")
X(variable_raw_ed,         "Variable-Rate Raw ED")

// From libdisk/format/ibm.c and ibm_img.c
X(ibm_pc_dd,              "IBM-PC DD (720kB)")
X(ibm_pc_dd_10sec,        "IBM-PC DD (800kB)")
X(ibm_pc_hd,              "IBM-PC HD (1.44MB)")
X(ibm_pc_hd_5_25,         "IBM-PC HD 5.25in")
X(ibm_pc_ed,              "IBM-PC ED")
 
X(ibm_fm_sd,              "IBM-FM SD")
X(ibm_fm_sd_recovery,     "IBM-FM SD Recovery Mode")
X(ibm_fm_dd,              "IBM-FM DD")

X(ibm_mfm_dd,             "IBM-MFM DD")
X(ibm_mfm_dd_recovery,    "IBM-MFM DD Recovery Mode")
X(ibm_mfm_hd,             "IBM-MFM HD")
X(ibm_mfm_ed,             "IBM-MFM ED")

X(dec_rx01,               "DEC-RX01 8in")
X(dec_rx02,               "DEC-RX02 8in")
X(dec_rx01_525,           "DEC-RX01 5.25in")
X(dec_rx02_525,           "DEC-RX02 5.25in")

X(acorn_adfs_s_m_l,       "Acorn ADFS '160K S', '320K M' or '640K L'")
X(acorn_adfs_d_e,         "Acorn ADFS '800K D' or '800K E'")
X(acorn_adfs_f,           "Acorn ADFS '1600K F'")

X(siemens_isdx_hd,        "Siemens iSDX high-density")
X(microsoft_dmf_hd,       "Microsoft DMF")
X(trace_traceback_hd,     "Trace TRACEBACK duplicator info (HD)")

// From libdisk/format/amiga/amigados.c
X(amigados,               "AmigaDOS")
X(amigados_extended,      "AmigaDOS Extended")
X(amigados_varrate,       "AmigaDOS Variable Rate")
X(amigados_long_102200,   "AmigaDOS Long Track (102200 Bits)")
X(amigados_long_103300,   "AmigaDOS Long Track (103300 Bits)")
X(amigados_long_104400,   "AmigaDOS Long Track (104400 Bits)")
X(amigados_long_105500,   "AmigaDOS Long Track (105500 Bits)")
X(amigados_long_106600,   "AmigaDOS Long Track (106600 Bits)")
X(amigados_long_108800,   "AmigaDOS Long Track (108800 Bits)")
X(amigados_long_111000,   "AmigaDOS Long Track (111000 Bits)")
X(amigados_unknown_length,"AmigaDOS (Unknown Length)")

// Required by libdisk/container/adf.c to read/write Amiga ADF images
X(rnc_dualformat,         "RNC Dual-Format")               // amiga/rnc_dualformat.c
X(rnc_dualformat_empty,   "RNC Dual-Format Empty Track")   // amiga/longtrack.c
X(tiertex_longtrack,      "Tiertex Copy Protection")       // Required by rnc_dualformat_empty
X(rnc_triformat,          "RNC Tri-Format")                // amiga/rnc_triformat.c
X(softlock_dualformat,    "SoftLock Dual Format")          // amiga/softlock_dualformat.c

// Required by libdisk/container/ipf.c to write-only SPS/CAPS IPF
X(speedlock,              "Speedlock")                     // amiga/speedlock.c
X(copylock,               "Copylock")                      // amiga/copylock.c
X(copylock_old,           "Copylock (Old)")                // amiga/copylock.c
X(copylock_old_variant,   "Copylock (Old, Variant)")       // amiga/copylock.c

/* Remove Sega and Amiga games protected formats
X(psygnosis_a, "Psygnosis A")
X(psygnosis_b, "Psygnosis B")
X(rnc_pdos, "RNC PDOS")
X(rnc_pdos_old, "RNC PDOS (Early Variant)")
X(core_design, "Core Design")
X(ss_mfm, "SS-MFM (Shaun Southern)")
X(protoscan_longtrack, "Protoscan")
X(protec_longtrack, "PROTEC")
X(rainbird, "Rainbird")
X(archipelagos, "Archipelagos")
X(alienbreed_protection, "Alien Breed Copy Protection")
X(blue_byte, "Blue Byte")
X(firebird, "Firebird")
X(ikplus, "IK+")
X(sensible, "Sensible Software")
X(rtype_a, "R-Type A")
X(rtype_b, "R-Type B")
X(kickoff2, "AmigaDOS (Kick Off 2 Long Track)")
X(silmarils_longtrack, "Silmarils/Lankhor Copy Protection")
X(psygnosis_c, "Psygnosis C")
X(psygnosis_c_track0, "Psygnosis C - Track 0")
X(psygnosis_c_custom_rll, "Psygnosis C - Custom RLL")
X(armourgeddon_a, "Armour-Geddon A")
X(armourgeddon_b, "Armour-Geddon B")
X(rnc_gap, "RNC Gap")
X(rnc_protect_process, "RNC (Protect Process)")
X(bat, "B.A.T.")
X(prolance_longtrack, "Prolance")
X(special_fx, "Special FX")
X(menace, "Menace")
X(infogrames_longtrack, "Infogrames Copy Protection")
X(turrican, "Turrican")
X(factor5_hiscore, "Factor 5 High Score")
X(federation_of_free_traders, "Federation Of Free Traders")
X(phantom_fighter, "Phantom Fighter")
X(zzkj_boot, "ZZKJ Bootloader")
X(zzkj_11sec, "ZZKJ 11-Sector")
X(bombuzal, "AmigaDOS (Bombuzal Long Track)")
X(ratt_dos_1800, "RattDOS")
X(ratt_dos_1810, "RattDOS")
X(pinball_dreams, "Pinball Dreams")
X(dungeon_master_weak, "Dungeon Master Weak Bits")
X(chaos_strikes_back_weak, "Chaos Strikes Back Weak Bits")
X(tlk_dos_1, "TLK-DOS-1")
X(tlk_dos_2, "TLK-DOS-2")
X(vade_retro_alienas, "Vade Retro Alienas")
X(sega_boot, "Sega Boot")
X(afterburner_sega, "After Burner (Sega)")
X(afterburner_data, "After Burner Data (Argonaut, Software Studios)")
X(albedo_protection, "Albedo Protection")
X(albedo_data, "Albedo Data")
X(outrun_sega, "Out Run (Sega)")
X(thunderblade_sega, "Thunder Blade (Sega)")
X(tracker, "Tracker")
X(adls, "ADLS")
X(dugger, "Dugger")
X(smartdos, "SmartDOS")
X(sega_system_24, "Sega System 24")
X(puffys_saga, "Puffy's Saga")
X(spherical, "Spherical")
X(grand_monster_slam, "Grand Monster Slam")
X(fun_factory, "Fun Factory")
X(eye_of_horus, "Eye Of Horus")
X(gladiators, "Gladiators")
X(trace_traceback_hd, "Trace TRACEBACK duplicator info (HD)")
X(baal, "Baal")
X(anarchy, "Anarchy")
X(spell_bound, "Spell Bound")
X(ork_a, "Ork A")
X(ork_b, "Ork B")
X(creatures_a, "Creatures A")
X(creatures_b, "Creatures B")
X(beastlord_a, "Beastlord A")
X(beastlord_b, "Beastlord B")
X(gadgetslostintime_a, "Gadgets Lost In Time - A")
X(gadgetslostintime_b, "Gadgets Lost In Time - B")
X(arc_development_a, "Arc Development A")
X(arc_development_b, "Arc Development B")
X(viaje, "Viaje Al Centro De La Tierra")
X(lorna, "Lorna")
X(shadow_beast, "Shadow of the Beast")
X(shadow_beast_2, "Shadow of the Beast II")
X(hellwig, "Hellwig")
X(apprentice, "Apprentice")
X(crackdown, "Crackdown")
X(elite_a, "Elite A")
X(elite_b, "Elite B")
X(elite_c, "Elite C")
X(elite_d, "Elite D")
X(fantastic_voyage, "Fantastic Voyage")
X(jinks, "Jinks Protection Track")
X(empty_longtrack, "Empty Long Track")
X(scooby_doo, "Scooby Doo And Scrappy Doo")
X(yogis_escape, "Yogi's Big Clean Up")
X(alien_world, "Alien World")
X(blazing_thunder, "Blazing Thunder")
X(hi_tec_b, "Hi-Tec B")
X(forgotten_worlds, "Forgotten Worlds")
X(blood_money, "Blood Money")
X(typhoon, "Typhoon Thompson")
X(denaris_a, "Denaris A")
X(denaris_b, "Denaris B")
X(conqueror,"Conqueror")
X(quartz_a, "Quartz A")
X(quartz_b, "Quartz B")
X(night_hunter_a, "Night Hunter A")
X(night_hunter_b, "Night Hunter B")
X(savage,"Savage")
X(vampires_empire_a,"Vampires Empire A")
X(vampires_empire_b,"Vampires Empire B")
X(vampires_empire_c,"Vampires Empire C")
X(skaermtrolden_hugo, "Skaermtrolden Hugo")
X(super_hang_on,"Super Hang-On")
X(super_hang_on_v2,"Super Hang-On (v2 format)")
X(super_hang_on_scores,"Super Hang-On Scores")
X(turbo1000cc_a,"1000cc Turbo A")
X(turbo1000cc_b,"1000cc Turbo B")
X(battle_squadron,"Battle Squadron")
X(nightdawn,"Nightdawn")
X(nightdawn_prot,"Nightdawn Protection")
X(deep_core, "Deep Core")
X(sink_or_swim, "Sink Or Swim")
X(behind_the_iron_gate, "Behind the Iron Gate")
X(kelloggs_land, "Tony & Friends in Kellogg's Land")
X(persian_gulf_inferno, "Persian Gulf Inferno")
X(app_longtrack, "Amiga Power Pack Copy Protection")
X(sextett_protection, "Sextett Copy Protection")
X(x_out, "X-Out")
X(cyberblast, "Cyberblast")
X(sevencities_longtrack, "Seven Cities Of Gold Protection")
X(robocod, "Robocod")
X(summer_games, "The Games: Summer Edition")
X(digital_magic, "Digital Magic Software")
X(prison, "Prison Copy Protection")
X(starray, "AmigaDOS (StarRay)")
X(speedball, "Speedball")
X(bump_n_burn, "Bump 'n' Burn")
X(konami,"Konami")
X(sword_sodan, "Sword of Sodan")
X(arkanoid_a,"Arkanoid A")
X(arkanoid_b,"Arkanoid B")
X(arkanoid_c,"Arkanoid C")
X(magic_marble,"Magic Marble")
X(magic_marble_b,"Magic Marble B")
X(magic_marble_prot,"Magic Marble Protection")
X(hybris,"Hybris")
X(zoom_a,"Zoom A")
X(zoom_b,"Zoom B")
X(globulus,"Globulus")
X(super_stardust, "Super Stardust")
X(silkworm, "Silkworm")
X(turrican_2, "Turrican II")
X(sales_curve, "Sales Curve")
X(ninja_warriors, "Ninja Warriors")
X(herndon_hls, "Herndon HLS")
X(turrican_3a, "Turrican 3 A")
X(turrican_3b, "Turrican 3 B")
X(turrican_3c, "Turrican 3 C")
X(head_over_heels, "Head Over Heels (Special FX)")
X(f1, "F1")
X(novagen, "Novagen")
X(xenon2, "Xenon 2")
X(xenon2_longtrack, "Xenon 2 Longtrack")
X(zeroes, "Zeroes Track")
X(supermethanebros_longtrack, "Super Methane Bros Long Track")
X(dyter_07, "Dyter-07")
X(ghost_battle, "Ghost Battle")
X(discoscopie, "Disco-Scopie")
X(intact, "Intact")
*/
